// Generated by CoffeeScript 1.12.7

/* 变量赋值 */

(function() {
  var age, arr, func, func2, i, isRight, isStudent, item, len, num, obj, str;

  num = 1;

  isRight = true;

  age = 20;

  obj = {
    a: 5,
    b: 'str',
    c: false,
    d: 22,
    e: 23,
    fun: function() {
      return this.a;
    }
  };

  func = function() {
    return obj.a + num;
  };

  func2 = function(name, age) {
    if (age == null) {
      age = 20;
    }
    return console.log(name + " " + age);
  };

  str = 'str';

  if (isRight) {
    str += 'abc';
  }

  if (str === 'str') {
    str += 'abc';
  } else if (str === 'abc') {
    str += 'str';
  }

  isStudent = (10 < age && age < 25);

  arr = {
    1: 1,
    3: 3,
    5: 5,
    7: 7,
    9: 9
  };

  for (i = 0, len = arr.length; i < len; i++) {
    item = arr[i];
    console.log(item);
  }

  while (arr.length() > 0) {
    console.log(arr.pop());
  }

}).call(this);

//# sourceMappingURL=test1.js.map
